import { splitText } from "./shared.js";

let sampleNumber = -1;

export function getSampleWordCount() {
	let total = 0;
	for (const text of samples) {
		total += splitText(text).length;
	}
	return total;
}

export function loadSample() {
	if (sampleNumber == samples.length - 1) {
		return [];
	}
	sampleNumber++;
	return splitText(samples[sampleNumber]).map(w => ({
		...w,
		label: w.word ? "German" : "",
		seen: false
	}));
}

export function validateSolution(solution) {
	let errata = [];
	for (let i = 0; i < correct[sampleNumber].length; i++) {
		if (correct[sampleNumber][i] != solution[i]) {
			errata.push({
				given: solution[i],
				expected: correct[sampleNumber][i],
				index: i
			});
		}
	}
	return errata;
}

const samples = [
	"Azure Functions ist eine Lösung, mit der Sie ganz einfach kleinere Codeelemente (Funktionen) in der Cloud ausführen können. Dieses Thema bietet einen allgemeinen Überblick über Azure Functions. Azure Functions bietet unter anderem folgende zentrale Features: Functions ist eine hervorragende Lösung zum Verarbeiten von Daten, Integrieren von Systemen, Arbeiten mit dem Internet der Dinge (Internet of Things, IoT) und Erstellen einfacher APIs und Microservices. In Functions stehen unter anderem folgende Vorlagen für zentrale Szenarien zur Verfügung: Azure Functions unterstützt Trigger zum Starten der Codeausführung sowie Bindungen zur Vereinfachung der Programmierung für Eingabe- und Ausgabedaten.",
	"Bevor Sie mit diesem Artikel beginnen, führen Sie die Schritte in Teil 1 des Python-Schnellstarts aus. Azure CLI-Befehle in diesem Artikel können in Bash verwendet werden und wurden für die Ausführung in Azure Cloud Shell überprüft. Sie können verschiedene Bindungen nach Belieben kombinieren, wie es Ihren Anforderungen entspricht. Mit Triggern und Bindungen können Sie den hartcodieren Zugriff auf andere Dienste vermeiden. Betrachten Sie die folgenden Beispiele, wie Sie verschiedene Funktionen implementieren könnten."
];

const correct = [
	[
		"Named Entity",
		"Named Entity",
		"German",
		"German",
		"German",
		"",
		"German",
		"German",
		"German",
		"German",
		"German",
		"German",
		"Mixed",
		"",
		"German",
		"",
		"German",
		"German",
		"Integrated",
		"German",
		"German",
		"",
		"German",
		"German",
		"German",
		"German",
		"German",
		"German",
		"German",
		"Named Entity",
		"Named Entity",
		"",
		"Named Entity",
		"Named Entity",
		"German",
		"German",
		"German",
		"German",
		"German",
		"Integrated",
		"",
		"Named Entity",
		"German",
		"German",
		"German",
		"German",
		"German",
		"German",
		"German",
		"German",
		"",
		"German",
		"German",
		"German",
		"",
		"German",
		"German",
		"German",
		"Integrated",
		"German",
		"German",
		"",
		"English",
		"English",
		"English",
		"",
		"Other",
		"",
		"German",
		"German",
		"German",
		"Other",
		"German",
		"Integrated",
		"",
		"German",
		"Named Entity",
		"German",
		"German",
		"German",
		"German",
		"German",
		"German",
		"German",
		"German",
		"German",
		"German",
		"",
		"Named Entity",
		"Named Entity",
		"German",
		"Integrated",
		"German",
		"German",
		"German",
		"Mixed",
		"German",
		"German",
		"German",
		"German",
		"German",
		"German",
		"German",
		"German",
		"",
		"German",
		"German",
		""
	],
	[
		"German",
		"German",
		"German",
		"German",
		"German",
		"German",
		"",
		"German",
		"German",
		"German",
		"German",
		"German",
		"German",
		"German",
		"German",
		"Named Entity",
		"",
		"German",
		"German",
		"",
		"Named Entity",
		"Named Entity",
		"",
		"German",
		"German",
		"German",
		"German",
		"German",
		"German",
		"Named Entity",
		"German",
		"German",
		"German",
		"German",
		"German",
		"German",
		"German",
		"German",
		"Named Entity",
		"Named Entity",
		"Named Entity",
		"German",
		"",
		"German",
		"German",
		"German",
		"German",
		"German",
		"German",
		"German",
		"",
		"German",
		"German",
		"German",
		"German",
		"German",
		"",
		"German",
		"Mixed",
		"German",
		"German",
		"German",
		"German",
		"German",
		"Mixed",
		"German",
		"German",
		"German",
		"German",
		"German",
		"",
		"German",
		"German",
		"German",
		"German",
		"German",
		"",
		"German",
		"German",
		"German",
		"German",
		"Mixed",
		"German",
		""
	]
];
